version: '3'
services:
  app:
    build: ./app
    command: ["bundle","exec","rackup","--host","0.0.0.0","--port","4567"]
    volumes:
      - ./app/:/app
  proxy:
    image: nginx
    command: ["nginx-debug", "-g", "daemon off;"]
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/my-site.com.crt:/etc/ssl/certs/my-site.com.crt # New Line!
      - ./proxy/my-site.com.key:/etc/ssl/private/my-site.com.key # New Line!
    ports:
      - 8080:80
      - "444:444" # Hey docker start listening on 443, and redirect to 443
    depends_on:
      - app
networks:
  default:
    name: janus-rails_default
# you can connect it to other docker network and use it with 

